apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: web-ui
    nodePort: 30200
    port: 8075
    targetPort: 8075
  - name: remote-java-protocol
    nodePort: 30300
    port: 50000
    targetPort: 50000docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts